### ISSUE TITLE
Error updating hosts file

### ISSUE THREAD

**Issue by mohsenSy** [ahmedfaragmostafa/dockerized_lara#1]
Hi, you have an error in your `README.md` file in `Update Hosts file section`

You cannot use `sudo echo ....` because echo is a built in not an executable binary file so cannot use sudo before it, you can use this command instead

```
echo "127.0.0.1 dockerized_lara.local" | sudo tee -a /etc/hosts
```

I hope you fix it quickly :+1:

**Comment by ahmedfaragmostafa** [comment]
Thanks @mohsenSy  [it's fixed now](https://github.com/ahmedfaragmostafa/dockerized_lara/pull/2) it is working, give it a try and let me know in case of you face in issues
